version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: node-devcontainer
    container_name: node-devcontainer
    ports:
      - '3001:3001'
    env_file:
      - .env
    volumes:
      - ./:/app
      - /app/node_modules
    restart: always
    tty: true
    stdin_open: true

volumes:
  node_modules:
